#!/bin/sh

CMD="./cc"
STATUS=0

test() {
	$CMD "$1/input.c" 2>&1 > "$1/last_output"
	cmp "$1/last_output" "$1/output" > /dev/null
	ret=$?
	if [ $ret = 0 ]; then
		echo "PASS: $1"
    else
		echo "FAIL: $1"
		STATUS=1
	fi
}

for test_folder in tests/*; do test "$test_folder"; done
exit "$STATUS"
